# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/C++/LearnToCode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/C++/LearnToCode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/C++/LearnToCode/CMakeFiles /data/data/com.termux/files/home/C++/LearnToCode//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/C++/LearnToCode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyLearningGame

# Build rule for target.
MyLearningGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyLearningGame
.PHONY : MyLearningGame

# fast build rule for target.
MyLearningGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/build
.PHONY : MyLearningGame/fast

src/game/Game.o: src/game/Game.cpp.o
.PHONY : src/game/Game.o

# target to build an object file
src/game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/game/Game.cpp.o
.PHONY : src/game/Game.cpp.o

src/game/Game.i: src/game/Game.cpp.i
.PHONY : src/game/Game.i

# target to preprocess a source file
src/game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/game/Game.cpp.i
.PHONY : src/game/Game.cpp.i

src/game/Game.s: src/game/Game.cpp.s
.PHONY : src/game/Game.s

# target to generate assembly for a file
src/game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/game/Game.cpp.s
.PHONY : src/game/Game.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/states/Lessons.o: src/states/Lessons.cpp.o
.PHONY : src/states/Lessons.o

# target to build an object file
src/states/Lessons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/Lessons.cpp.o
.PHONY : src/states/Lessons.cpp.o

src/states/Lessons.i: src/states/Lessons.cpp.i
.PHONY : src/states/Lessons.i

# target to preprocess a source file
src/states/Lessons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/Lessons.cpp.i
.PHONY : src/states/Lessons.cpp.i

src/states/Lessons.s: src/states/Lessons.cpp.s
.PHONY : src/states/Lessons.s

# target to generate assembly for a file
src/states/Lessons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/Lessons.cpp.s
.PHONY : src/states/Lessons.cpp.s

src/states/Terminal.o: src/states/Terminal.cpp.o
.PHONY : src/states/Terminal.o

# target to build an object file
src/states/Terminal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/Terminal.cpp.o
.PHONY : src/states/Terminal.cpp.o

src/states/Terminal.i: src/states/Terminal.cpp.i
.PHONY : src/states/Terminal.i

# target to preprocess a source file
src/states/Terminal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/Terminal.cpp.i
.PHONY : src/states/Terminal.cpp.i

src/states/Terminal.s: src/states/Terminal.cpp.s
.PHONY : src/states/Terminal.s

# target to generate assembly for a file
src/states/Terminal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/Terminal.cpp.s
.PHONY : src/states/Terminal.cpp.s

src/states/menu.o: src/states/menu.cpp.o
.PHONY : src/states/menu.o

# target to build an object file
src/states/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/menu.cpp.o
.PHONY : src/states/menu.cpp.o

src/states/menu.i: src/states/menu.cpp.i
.PHONY : src/states/menu.i

# target to preprocess a source file
src/states/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/menu.cpp.i
.PHONY : src/states/menu.cpp.i

src/states/menu.s: src/states/menu.cpp.s
.PHONY : src/states/menu.s

# target to generate assembly for a file
src/states/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/states/menu.cpp.s
.PHONY : src/states/menu.cpp.s

src/text/Delays.o: src/text/Delays.cpp.o
.PHONY : src/text/Delays.o

# target to build an object file
src/text/Delays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/text/Delays.cpp.o
.PHONY : src/text/Delays.cpp.o

src/text/Delays.i: src/text/Delays.cpp.i
.PHONY : src/text/Delays.i

# target to preprocess a source file
src/text/Delays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/text/Delays.cpp.i
.PHONY : src/text/Delays.cpp.i

src/text/Delays.s: src/text/Delays.cpp.s
.PHONY : src/text/Delays.s

# target to generate assembly for a file
src/text/Delays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/text/Delays.cpp.s
.PHONY : src/text/Delays.cpp.s

src/text/Type.o: src/text/Type.cpp.o
.PHONY : src/text/Type.o

# target to build an object file
src/text/Type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/text/Type.cpp.o
.PHONY : src/text/Type.cpp.o

src/text/Type.i: src/text/Type.cpp.i
.PHONY : src/text/Type.i

# target to preprocess a source file
src/text/Type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/text/Type.cpp.i
.PHONY : src/text/Type.cpp.i

src/text/Type.s: src/text/Type.cpp.s
.PHONY : src/text/Type.s

# target to generate assembly for a file
src/text/Type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/text/Type.cpp.s
.PHONY : src/text/Type.cpp.s

src/user/User.o: src/user/User.cpp.o
.PHONY : src/user/User.o

# target to build an object file
src/user/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/user/User.cpp.o
.PHONY : src/user/User.cpp.o

src/user/User.i: src/user/User.cpp.i
.PHONY : src/user/User.i

# target to preprocess a source file
src/user/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/user/User.cpp.i
.PHONY : src/user/User.cpp.i

src/user/User.s: src/user/User.cpp.s
.PHONY : src/user/User.s

# target to generate assembly for a file
src/user/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyLearningGame.dir/build.make CMakeFiles/MyLearningGame.dir/src/user/User.cpp.s
.PHONY : src/user/User.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyLearningGame"
	@echo "... src/game/Game.o"
	@echo "... src/game/Game.i"
	@echo "... src/game/Game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/states/Lessons.o"
	@echo "... src/states/Lessons.i"
	@echo "... src/states/Lessons.s"
	@echo "... src/states/Terminal.o"
	@echo "... src/states/Terminal.i"
	@echo "... src/states/Terminal.s"
	@echo "... src/states/menu.o"
	@echo "... src/states/menu.i"
	@echo "... src/states/menu.s"
	@echo "... src/text/Delays.o"
	@echo "... src/text/Delays.i"
	@echo "... src/text/Delays.s"
	@echo "... src/text/Type.o"
	@echo "... src/text/Type.i"
	@echo "... src/text/Type.s"
	@echo "... src/user/User.o"
	@echo "... src/user/User.i"
	@echo "... src/user/User.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

